// @vitest-environment happy-dom

import { describe, expect, it, vi } from "vitest";
import {
  PairingSetupClient,
  pairingCompletionUrl,
  pairingLegacySessionUrl,
  pairingSessionUrl,
  parsePublicPairingRequest,
  readVillageCsrfCookie,
} from "../pairing-setup-client.js";

const publicRequest = {
  deviceId: "dev_01J00000000000000000000000",
  deviceDisplayName: "Andrew's Mac",
  publicKey: {
    kty: "OKP" as const,
    crv: "Ed25519" as const,
    x: "cHVibGljX2tleQ",
  },
  protection: "OS_PROTECTED_FALLBACK" as const,
  secretHash: "a".repeat(43),
};
const challenge = {
  principalId: "prn_01J00000000000000000000000",
  pairingId: "par_01J00000000000000000000000",
  deviceId: publicRequest.deviceId,
  fingerprint: "A1B2C3D4E5F60708",
  expiresAt: "2026-08-13T13:05:00.000Z",
};

describe("pairing setup client", () => {
  it("uses an issued development CSRF cookie before the local fallback", () => {
    document.cookie =
      "village_csrf=csrf-owner-ceremony-proof-token-00000008; Path=/";
    expect(readVillageCsrfCookie()).toBe(
      "csrf-owner-ceremony-proof-token-00000008",
    );
  });

  it("accepts only an exact public request and never requires the secret", () => {
    expect(parsePublicPairingRequest(JSON.stringify(publicRequest))).toEqual(
      publicRequest,
    );
    expect(() =>
      parsePublicPairingRequest(
        JSON.stringify({ ...publicRequest, secret: "do-not-send" }),
      ),
    ).toThrow("PAIRING_REQUEST_INVALID");
  });

  it("accepts a public request generated by the packaged desktop", () => {
    expect(
      parsePublicPairingRequest(
        JSON.stringify({
          deviceId: "dev_73KWN11WG5B5WVXX0X2CK7PQK3",
          deviceDisplayName: "As-Mac-Studio.local",
          publicKey: {
            kty: "OKP",
            crv: "Ed25519",
            x: "NjwyMc7XG9IrUQX83gBIYXvdNOWp5jz_jTtK7Zd9Sbg",
          },
          protection: "OS_PROTECTED_FALLBACK",
          secretHash: "EXEVBhnkI6EFNuwUFhf_XPtKgwsrR4jX1AAflweBQ5M",
        }),
      ),
    ).toMatchObject({
      deviceId: "dev_73KWN11WG5B5WVXX0X2CK7PQK3",
      protection: "OS_PROTECTED_FALLBACK",
    });
  });

  it("begins, confirms, polls, and creates distinct personal and continuity sessions with CSRF", async () => {
    const request = vi
      .fn<typeof fetch>()
      .mockResolvedValueOnce(
        Response.json({ ok: true, ...challenge }, { status: 201 }),
      )
      .mockResolvedValueOnce(Response.json({ ok: true }))
      .mockResolvedValueOnce(
        Response.json({ ok: true, pairing: { state: "CONSUMED" } }),
      )
      .mockResolvedValueOnce(
        Response.json(
          { ok: true, jobId: "job_01J00000000000000000000000" },
          { status: 201 },
        ),
      )
      .mockResolvedValueOnce(Response.json({ ok: true }, { status: 201 }))
      .mockResolvedValueOnce(
        Response.json(
          { ok: true, jobId: "job_01J00000000000000000000001" },
          { status: 201 },
        ),
      )
      .mockResolvedValueOnce(Response.json({ ok: true }, { status: 201 }));
    const client = new PairingSetupClient(
      "https://village.test",
      request,
      () => "csrf-token-that-is-at-least-thirty-two-bytes-long",
    );

    await expect(client.begin(publicRequest)).resolves.toEqual(challenge);
    await client.confirm(challenge.pairingId);
    await expect(client.status(challenge.pairingId)).resolves.toBe("CONSUMED");
    const session = await client.createSession(publicRequest.deviceId);

    expect(request.mock.calls.map(([url]) => String(url))).toEqual([
      "https://village.test/api/pairing/challenges",
      `https://village.test/api/pairing/${challenge.pairingId}/confirm`,
      `https://village.test/api/pairing/${challenge.pairingId}`,
      "https://village.test/api/jobs",
      "https://village.test/api/jobs/job_01J00000000000000000000000/browser-sessions",
      "https://village.test/api/jobs",
      "https://village.test/api/jobs/job_01J00000000000000000000001/browser-sessions",
    ]);
    const sessionBody = JSON.parse(String(request.mock.calls[4]![1]?.body));
    expect(sessionBody).toMatchObject({
      deviceId: publicRequest.deviceId,
      site: "LINKEDIN",
    });
    const continuityBody = JSON.parse(String(request.mock.calls[6]![1]?.body));
    expect(continuityBody).toMatchObject({
      deviceId: publicRequest.deviceId,
      site: "OWNED_FIXTURE",
    });
    expect(session.browserSessionId).toMatch(/^brs_[0-9A-HJKMNP-TV-Z]{26}$/);
    expect(session.hostId).toMatch(/^hst_[0-9A-HJKMNP-TV-Z]{26}$/);
    expect(session.fixtureBrowserSessionId).toMatch(
      /^brs_[0-9A-HJKMNP-TV-Z]{26}$/,
    );
    expect(session.fixtureBrowserSessionId).not.toBe(session.browserSessionId);
    expect(
      new Headers(request.mock.calls[0]![1]?.headers).get("x-village-csrf"),
    ).toBe("csrf-token-that-is-at-least-thirty-two-bytes-long");
  });

  it("builds credential-free custom protocol links", () => {
    const completion = pairingCompletionUrl(challenge);
    const session = pairingSessionUrl(challenge, {
      jobId: "job_01J00000000000000000000000",
      browserSessionId: "brs_01J00000000000000000000000",
      hostId: "hst_01J00000000000000000000000",
      fixtureBrowserSessionId: "brs_01J00000000000000000000001",
    });
    expect(completion).toContain(`pairingId=${challenge.pairingId}`);
    expect(session).toContain(
      "browserSessionId=brs_01J00000000000000000000000",
    );
    expect(session).toContain(
      "fixtureBrowserSessionId=brs_01J00000000000000000000001",
    );
    expect(`${completion}${session}`).not.toContain("secret");
  });

  it("offers a legacy session link without enabling continuity", () => {
    const session = pairingLegacySessionUrl(challenge, {
      jobId: "job_01J00000000000000000000000",
      browserSessionId: "brs_01J00000000000000000000000",
      hostId: "hst_01J00000000000000000000000",
      fixtureBrowserSessionId: "brs_01J00000000000000000000001",
    });

    expect(session).toContain(
      "browserSessionId=brs_01J00000000000000000000000",
    );
    expect(session).not.toContain("fixtureBrowserSessionId");
  });

  it("resumes fixture provisioning without repeating the personal session", async () => {
    const request = vi
      .fn<typeof fetch>()
      .mockResolvedValueOnce(
        Response.json(
          { ok: true, jobId: "job_01J00000000000000000000000" },
          { status: 201 },
        ),
      )
      .mockResolvedValueOnce(Response.json({ ok: true }, { status: 201 }))
      .mockResolvedValueOnce(
        Response.json(
          { ok: false, code: "FIXTURE_TEMPORARILY_UNAVAILABLE" },
          { status: 503 },
        ),
      )
      .mockResolvedValueOnce(
        Response.json(
          { ok: true, jobId: "job_01J00000000000000000000001" },
          { status: 201 },
        ),
      )
      .mockResolvedValueOnce(Response.json({ ok: true }, { status: 201 }));
    const client = new PairingSetupClient(
      "https://village.test",
      request,
      () => "csrf-token-that-is-at-least-thirty-two-bytes-long",
    );

    await expect(client.createSession(publicRequest.deviceId)).rejects.toThrow(
      "FIXTURE_TEMPORARILY_UNAVAILABLE",
    );
    await expect(
      client.createSession(publicRequest.deviceId),
    ).resolves.toMatchObject({
      jobId: "job_01J00000000000000000000000",
      fixtureBrowserSessionId: expect.stringMatching(/^brs_/),
    });

    expect(
      request.mock.calls.filter(([url]) => String(url).endsWith("/api/jobs")),
    ).toHaveLength(3);
    expect(
      request.mock.calls.filter(([, options]) => {
        if (!options?.body) return false;
        return JSON.parse(String(options.body)).site === "LINKEDIN";
      }),
    ).toHaveLength(1);
  });
});
