ALTER TABLE devices ADD COLUMN algorithm TEXT NOT NULL DEFAULT 'Ed25519'
  CHECK (algorithm IN ('Ed25519', 'ES256'));
ALTER TABLE devices ADD COLUMN credential_protection TEXT NOT NULL
  DEFAULT 'OS_PROTECTED_FALLBACK'
  CHECK (credential_protection IN ('HARDWARE_NON_EXPORTABLE', 'OS_PROTECTED_FALLBACK'));
